/* Fosterhub operational module enhancements
   Uses the existing Supabase client and schema. No service-role key is used. */
(function(){
  const wait = fn => document.readyState === 'loading' ? document.addEventListener('DOMContentLoaded', fn) : fn();
  const esc = v => typeof escapeHtml === 'function' ? escapeHtml(v) : String(v ?? '').replace(/[&<>\"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
  const fmtMoney = v => '$' + Number(v || 0).toFixed(2);
  const msg = (text, ok=false) => { let n=document.getElementById('fhToast'); if(!n){n=document.createElement('div');n.id='fhToast';Object.assign(n.style,{position:'fixed',right:'20px',bottom:'20px',zIndex:9999,maxWidth:'420px',padding:'14px 18px',borderRadius:'10px',background:'#16233d',color:'#fff',boxShadow:'0 8px 25px #0003'});document.body.appendChild(n);} n.textContent=text;n.style.background=ok?'#2e8b62':'#c94b4b';n.style.display='block';clearTimeout(n._t);n._t=setTimeout(()=>n.style.display='none',3500);};
  const q = id => document.getElementById(id);
  const shell = (id,title,controls,tableId,heads) => { const s=q(id); if(!s)return null; s.innerHTML=`<div class="panel"><div style="display:flex;justify-content:space-between;gap:12px;align-items:center;flex-wrap:wrap"><h2>${title}</h2><div>${controls||''}</div></div><div id="${id}Status" class="empty" style="display:none"></div><div style="overflow:auto"><table class="table"><thead><tr>${heads.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody id="${tableId}"><tr><td colspan="${heads.length}" class="empty">Loading...</td></tr></tbody></table></div></div>`; return s; };
  const button = (text,fn,primary=true) => { const b=document.createElement('button');b.className=primary?'primary-btn':'secondary-btn';b.textContent=text;b.onclick=fn;return b; };
  const field = (label,id,type='text',extra='') => `<div class="form-group"><label>${label}</label><input id="${id}" type="${type}" ${extra}></div>`;
  const select = (label,id,opts) => `<div class="form-group"><label>${label}</label><select id="${id}">${opts.map(o=>`<option value="${esc(o[0])}">${esc(o[1])}</option>`).join('')}</select></div>`;
  function modal(title,html,onSave){
    const old=q('fhModal'); if(old)old.remove(); const m=document.createElement('div');m.id='fhModal';Object.assign(m.style,{position:'fixed',inset:0,zIndex:9998,background:'#0007',display:'flex',alignItems:'center',justifyContent:'center',padding:'20px'});m.innerHTML=`<div style="background:#fff;border-radius:16px;width:min(760px,100%);max-height:90vh;overflow:auto;padding:22px"><div style="display:flex;justify-content:space-between;align-items:center"><h2 style="margin-top:0">${title}</h2><button id="fhClose" class="secondary-btn">✕</button></div>${html}<div style="display:flex;gap:10px;justify-content:flex-end"><button id="fhCancel" class="secondary-btn">Cancel</button><button id="fhSave" class="primary-btn">Save</button></div></div>`;document.body.appendChild(m);q('fhClose').onclick=q('fhCancel').onclick=()=>m.remove();q('fhSave').onclick=async()=>{const b=q('fhSave');b.disabled=true;try{await onSave();m.remove();}catch(e){msg(e.message||'Unable to save');b.disabled=false;}};return m;
  }
  async function rows(table, select='*', order='created_at', ascending=false){ const {data,error}=await client.from(table).select(select).order(order,{ascending}); if(error)throw error; return data||[]; }

  async function owners(){
    const data=await rows('owners'); const body=q('ownersBody'); if(!body)return; body.innerHTML=data.length?data.map(o=>`<tr><td><strong>${esc(o.first_name)} ${esc(o.last_name||'')}</strong></td><td>${esc(o.phone||'—')}</td><td>${esc(o.email||'—')}</td><td>${esc(o.case_reason||'—')}</td><td>${esc(o.expected_availability_date||'—')}</td><td><button class="secondary-btn" onclick="fhEditOwner('${o.id}')">Edit</button></td></tr>`).join(''):`<tr><td colspan="6" class="empty">No owners yet.</td></tr>`;
  }
  window.fhEditOwner=async id=>{const {data:o,error}=await client.from('owners').select('*').eq('id',id).single();if(error)return msg(error.message);modal('Edit Owner',`<div class="dog-form-grid">${field('First name','fo','text','required')}${field('Last name','lo')}${field('Phone','po','tel')}${field('Email','eo','email')}${select('Preferred contact','co',[['phone','Phone'],['text','Text'],['email','Email'],['other','Other']])}${field('Case reason','ro')}${field('Expected availability','ao','date')}</div><div class="form-group"><label>Reunification notes</label><textarea id="no" rows="4"></textarea></div>`,async()=>{const {error}=await client.from('owners').update({first_name:q('fo').value.trim(),last_name:q('lo').value.trim()||null,phone:q('po').value.trim()||null,email:q('eo').value.trim()||null,preferred_contact:q('co').value||null,case_reason:q('ro').value.trim()||null,expected_availability_date:q('ao').value||null,reunification_notes:q('no').value.trim()||null,updated_at:new Date().toISOString()}).eq('id',id);if(error)throw error;await owners();msg('Owner updated.',true);}); q('fo').value=o.first_name||'';q('lo').value=o.last_name||'';q('po').value=o.phone||'';q('eo').value=o.email||'';q('co').value=o.preferred_contact||'phone';q('ro').value=o.case_reason||'';q('ao').value=o.expected_availability_date||'';q('no').value=o.reunification_notes||'';};

  async function placements(){
    const data=await rows('placements','*,dogs(name)','start_date',false);const body=q('placementsBody');if(!body)return;body.innerHTML=data.length?data.map(p=>`<tr><td>${esc(p.dogs?.name||'Unknown')}</td><td>${esc(p.foster_id)}</td><td>${esc(p.start_date)}</td><td>${esc(p.expected_end_date||'—')}</td><td><span class="pill ${p.status==='active'?'green':'blue'}">${esc(p.status)}</span></td></tr>`).join(''):`<tr><td colspan="5" class="empty">No placements yet.</td></tr>`;
  }
  async function checkins(){
    const data=await rows('foster_checkins','*,dogs(name)','due_date',true);const body=q('checkinsBody');if(!body)return;body.innerHTML=data.length?data.map(c=>`<tr><td>${esc(c.dogs?.name||'Unknown')}</td><td>${esc(c.foster_id)}</td><td>${esc(c.due_date)}</td><td>${c.completed_at?'<span class="pill green">Completed</span>':'<span class="pill blue">Due</span>'}</td><td>${c.medical_concern||c.behavioral_change||c.needs_assistance?'<span class="pill" style="background:#ffe9e9;color:#a33">Needs attention</span>':'OK'}</td><td><button class="secondary-btn" onclick="fhCompleteCheckin('${c.id}')">Complete</button></td></tr>`).join(''):`<tr><td colspan="6" class="empty">No check-ins yet.</td></tr>`;
  }
  window.fhCompleteCheckin=async id=>{const {error}=await client.from('foster_checkins').update({completed_at:new Date().toISOString()}).eq('id',id);if(error)return msg(error.message);await checkins();msg('Check-in completed.',true);};
  async function medical(){
    const [v,m,vis]=await Promise.all([rows('vaccinations','*,dogs(name)','administered_date',false),rows('medications','*,dogs(name)','created_at',false),rows('vet_visits','*,dogs(name)','appointment_date',false)]);const body=q('medicalBody');if(!body)return;const all=[...v.map(x=>({date:x.administered_date,type:'Vaccination',dog:x.dogs?.name,detail:x.vaccine_name,extra:x.expiration_date})),...m.map(x=>({date:x.start_date,type:'Medication',dog:x.dogs?.name,detail:x.medication_name,extra:x.dosage||''})),...vis.map(x=>({date:x.appointment_date,type:'Vet visit',dog:x.dogs?.name,detail:x.reason||'Visit',extra:x.diagnosis||''}))].sort((a,b)=>String(b.date).localeCompare(String(a.date)));body.innerHTML=all.length?all.map(x=>`<tr><td>${esc(x.date||'—')}</td><td>${esc(x.dog||'Unknown')}</td><td>${esc(x.type)}</td><td>${esc(x.detail||'—')}</td><td>${esc(x.extra||'—')}</td></tr>`).join(''):`<tr><td colspan="5" class="empty">No medical records yet.</td></tr>`;
  }
  async function expenses(){const data=await rows('expenses','*,dogs(name)','expense_date',false);const body=q('expensesBody');if(!body)return;const total=data.reduce((s,x)=>s+Number(x.amount||0),0);q('expenseTotal').textContent=fmtMoney(total);body.innerHTML=data.length?data.map(x=>`<tr><td>${esc(x.expense_date)}</td><td>${esc(x.dogs?.name||'General')}</td><td>${esc(x.category)}</td><td>${esc(x.description||'—')}</td><td>${fmtMoney(x.amount)}</td></tr>`).join(''):`<tr><td colspan="5" class="empty">No expenses recorded.</td></tr>`;}
  async function documents(){const data=await rows('documents','*','created_at',false);const body=q('documentsBody');if(!body)return;body.innerHTML=data.length?data.map(d=>`<tr><td>${esc(d.file_name)}</td><td>${esc(d.document_type)}</td><td>${esc(d.dog_id||d.owner_id||d.foster_id||'—')}</td><td>${esc(new Date(d.created_at).toLocaleDateString())}</td><td><a class="primary-btn" href="${esc(d.file_url)}" target="_blank" rel="noopener">Open</a></td></tr>`).join(''):`<tr><td colspan="5" class="empty">No documents recorded.</td></tr>`;}
  async function volunteers(){const data=await rows('volunteers');const body=q('volunteersBody');if(!body)return;body.innerHTML=data.length?data.map(v=>`<tr><td>${esc(v.id)}</td><td>${esc(v.skills||'—')}</td><td>${v.transportation_available?'Yes':'No'}</td><td>${esc(v.availability||'—')}</td><td>${esc(v.preferred_tasks||'—')}</td></tr>`).join(''):`<tr><td colspan="5" class="empty">No volunteers yet.</td></tr>`;}
  async function needs(){const data=await rows('volunteer_needs','*','created_at',false);const body=q('needsBody');if(!body)return;body.innerHTML=data.length?data.map(n=>`<tr><td><strong>${esc(n.title)}</strong><br><small>${esc(n.description||'')}</small></td><td>${esc(n.category)}</td><td>${esc(n.location||'—')}</td><td>${esc(n.due_date||'—')}</td><td><span class="pill ${n.urgency==='urgent'?'red':'blue'}">${esc(n.urgency)}</span></td><td>${esc(n.status)}</td></tr>`).join(''):`<tr><td colspan="6" class="empty">No volunteer needs posted.</td></tr>`;}
  async function reports(){const [d,f,p,e,c]=await Promise.all([rows('dogs'),rows('fosters'),rows('placements'),rows('expenses'),rows('foster_checkins')]);const total=e.reduce((s,x)=>s+Number(x.amount||0),0);q('reportsBody').innerHTML=`<tr><td>Dogs</td><td>${d.length}</td></tr><tr><td>Foster homes</td><td>${f.length}</td></tr><tr><td>Active placements</td><td>${p.filter(x=>x.status==='active').length}</td></tr><tr><td>Total tracked expenses</td><td>${fmtMoney(total)}</td></tr><tr><td>Open check-ins</td><td>${c.filter(x=>!x.completed_at).length}</td></tr>`;}
  async function users(){const data=await rows('profiles','*','created_at',false);const body=q('usersBody');if(!body)return;body.innerHTML=data.length?data.map(u=>`<tr><td>${esc(u.first_name||'')} ${esc(u.last_name||'')}</td><td>${esc(u.email||'')}</td><td><span class="pill blue">${esc(u.role)}</span></td><td>${u.active?'<span class="pill green">Active</span>':'Inactive'}</td></tr>`).join(''):`<tr><td colspan="4" class="empty">No profiles found.</td></tr>`;}

  function build(){
    shell('owners','👤 Owners & Reunification','', 'ownersBody',['Owner','Phone','Email','Case reason','Expected availability','']);
    const op=button('+ Add Owner',()=>modal('Add Owner',`<div class="dog-form-grid">${field('First name','fo','text','required')}${field('Last name','lo')}${field('Phone','po','tel')}${field('Email','eo','email')}${select('Preferred contact','co',[['phone','Phone'],['text','Text'],['email','Email'],['other','Other']])}${field('Case reason','ro')}${field('Expected availability','ao','date')}</div><div class="form-group"><label>Reunification notes</label><textarea id="no" rows="4"></textarea></div>`,async()=>{const {error}=await client.from('owners').insert({first_name:q('fo').value.trim(),last_name:q('lo').value.trim()||null,phone:q('po').value.trim()||null,email:q('eo').value.trim()||null,preferred_contact:q('co').value,case_reason:q('ro').value.trim()||null,expected_availability_date:q('ao').value||null,reunification_notes:q('no').value.trim()||null});if(error)throw error;await owners();msg('Owner added.',true);}));q('owners').querySelector('h2').after(op);
    shell('checkins','📋 Foster Check-ins','', 'checkinsBody',['Dog','Foster','Due','Status','Flags','Action']);
    shell('medical','💊 Medical','', 'medicalBody',['Date','Dog','Record','Details','Additional']);
    shell('expenses','💰 Expenses','', 'expensesBody',['Date','Dog','Category','Description','Amount']);q('expenses').querySelector('h2').insertAdjacentHTML('afterend','<div class="row" style="margin:8px 0 16px"><span>Total tracked</span><strong id="expenseTotal">$0.00</strong></div>');
    shell('documents','📁 Documents','', 'documentsBody',['File','Type','Linked record','Date','Open']);
    shell('volunteers','🙋 Volunteers','', 'volunteersBody',['Volunteer','Skills','Transportation','Availability','Preferred tasks']);
    shell('needs','📢 Volunteer Needs','', 'needsBody',['Need','Category','Location','Due','Urgency','Status']);
    shell('reports','📊 Reports','', 'reportsBody',['Metric','Value']);
    shell('users','⚙️ Users & Permissions','', 'usersBody',['Name','Email','Role','Status']);
  }
  async function refreshAll(){try{await Promise.all([owners(),placements(),checkins(),medical(),expenses(),documents(),volunteers(),needs(),reports(),users()]);}catch(e){console.error(e);msg('Some Fosterhub data could not be loaded: '+e.message);}}
  wait(()=>{build();setTimeout(refreshAll,2500);if(window.client){client.auth.onAuthStateChange((event,session)=>{if(session)setTimeout(refreshAll,500);});}});
})();
